### ISSUE TITLE
Command + click not working

### ISSUE THREAD

**Issue by Ebtoulson** [rentpath/jquery-autotagging.js#21]
Command + clicking on an anchor tag does not open the link in a new tab but instead navigates the current window to the specified href.

Note: I have not tested this on windows (ctrl + click).

**Comment by mpelzsherman** [comment]
Apparently this is a common enough problem that somebody wrote an [extension](https://chrome.google.com/webstore/detail/command-click-fix/leklllfdadjjglhllebogdjfdipdjhhp) for it.

Should we wait until after we integrate [Tealium](http://tealium.com/) to address this?

**Comment by c0** [comment]
The root cause is that [`preventDefault`](https://github.com/primedia/jquery-autotagging/blob/dev/src/click_handler.coffee#L68) stops the native behavior and autotagging fires its own [`window.open`](https://github.com/primedia/jquery-autotagging/blob/dev/src/click_handler.coffee#L70).

I can see this being resolved two way –
1) The quick way is to look at the modifier key and open a window.
2) The more reliable way is to let the browser control opening a window by default (i.e. remove `preventDefault`). This requires checking that the tag still fires when the page changes quickly.

**Comment by c0** [comment]
#26 removes `preventDefault`
